config/routes.rb
Rails.application.routes.draw do

  get '/contatos' => 'contatos#index', as: :contatos

  resources :products, only: [:index, :show] do

    member do 
      get :like  
      get :dislike
    end

  end

  namespace :admin do
  	root 'products#index'
    
    resources :categories do
      member do
        patch :ativar   
        patch :desativar
        patch :change_status 
      end

      collection do

      end
    end

    resources :posts
    resources :products
    resources :users
  end

  devise_for :users, controllers: {:registrations => "users/registrations"}

  root 'products#index'
end

app/models/category.rb
class Category < ActiveRecord::Base

	## RELATIONSHIPS
	has_many :products


	## VALIDATIONS
	validates :name, presence: true
	validates :name, length: { minimum: 5, maximum: 25 }
end

app/controllers/admin/categories_controller.rb
class  Admin::CategoriesController < AdminController
	before_action :set_category, only: [:show, :edit, :update, :destroy, :ativar, :desativar, :change_status]

	def index
		@categories = Category.all
	end

	def show
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		
		if @category.save
			redirect_to admin_categories_path, notice: 'A categoria foi cadastrada com sucesso!'
		else
			render :new
		end

	end

	def edit
		
	end

	def update
		if @category.update(category_params)
			redirect_to admin_categories_path, notice: 'A categoria foi atualizada com sucesso!'
		else
			render :edit
		end
	end

	def destroy
		@category.destroy
		redirect_to admin_categories_path, notice: 'A categoria foi excluída com sucesso!'

	end

	def ativar
		@category.update(status: true)
		redirect_to admin_categories_path, notice: 'A categoria foi ativada com sucesso!'
	end

	def desativar
		@category.update(status: false)
		redirect_to admin_categories_path, notice: 'A categoria foi desativada com sucesso!'
	end

	def change_status
		if @category.status == true
			@category.update(status: false)
			redirect_to admin_categories_path, notice: 'A categoria foi desativada com sucesso!'
		else
			@category.update(status: true)
			redirect_to admin_categories_path, notice: 'A categoria foi ativada com sucesso!'			
		end
	end

	private

		def set_category
			@category = Category.find(params[:id])
		end

		def category_params
			params.require(:category).permit(:name, :status)
		end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_action :set_category, only: [:show, :edit, :update, :destroy]


	def index
		@categories = Category.all
	end

	def show
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		
		if @category.save
			redirect_to categories_path, notice: 'A categoria foi cadastrada com sucesso!'
		else
			render :new
		end

	end

	def edit
		
	end

	def update
		if @category.update(category_params)
			redirect_to categories_path, notice: 'A categoria foi atualizada com sucesso!'
		else
			render :edit
		end
	end

	def destroy
		@category.destroy
		redirect_to categories_path, notice: 'A categoria foi excluída com sucesso!'

	end

	private

		def set_category
			@category = Category.find(params[:id])
		end

		def category_params
			params.require(:category).permit(:name, :status)
		end

end

app/views/admin/categories/_form.html.erb
<%= simple_form_for [:admin, @category], :html => { :class => 'form-vertical' } do |f| %>
  <%= f.input :name %>
  <%= f.input :status %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_categories_path, :class => 'btn btn-default' %>
<% end %>

app/views/admin/categories/edit.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/categories/index.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <%= link_to t('.new', :default => t("helpers.links.new")), new_admin_category_path, :class => 'btn btn-primary pull-right' %>
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.id, admin_category_path(category) %></td>
        <td><%= category.name %></td>
        <td><%=show_status category.status %></td>
        <td><%=l category.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_category_path(category), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_category_path(category),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
          

          <% if category.status == true -%>
            <%= link_to "Desativar", change_status_admin_category_path(category), class: 'btn btn-xs btn-danger', method: :patch %>
          <% else -%>
            <%= link_to "Ativar", change_status_admin_category_path(category), class: 'btn btn-xs btn-success', method: :patch %>
          <% end -%>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/categories/new.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/categories/show.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @category.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @category.status %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              admin_categories_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_category_path(@category), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_category_path(@category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>