config/routes.rb
Rails.application.routes.draw do

  get '/contatos' => 'contatos#index', as: :contatos

  resources :products, only: [:index, :show] do

    member do 
      get :like  
      get :dislike
    end

  end

  namespace :admin do
  	root 'products#index'
    
    resources :categories do
      member do
        patch :ativar   
        patch :desativar
        patch :change_status 
      end

      collection do

      end
    end

    resources :posts
    resources :products
    resources :users
  end

  devise_for :users, controllers: {:registrations => "users/registrations"}

  root 'products#index'
end

app/models/product.rb
class Product < ActiveRecord::Base

	## RELATIONSHIPS
	belongs_to :category
	has_many :likes

	## VALIDATIONS
	validates :category_id, presence: true

	## SCOPE
	scope :published, -> { where(status: true) }
	scope :unpublished, -> { where(status: false) }

	## PRICE_VIEW

	def price_view
		if price_promo.present?
			price_promo
		else
			price
		end
	end

end

app/controllers/admin/products_controller.rb
class  Admin::ProductsController < AdminController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to [:admin, @product], notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to [:admin, @product], notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:category_id, :name, :description, :price, :price_promo, :status)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:like, :dislike]
  before_action :set_product, only: [:show, :like, :dislike]

  def index
    @products = Product.published
  end

  def show
  end

  def like
    if @product.likes.create!(user: current_user)
      redirect_to :back, notice: "Liked!!"
    else
      redirect_to :back, notice: "Error: No Liked!"
    end
  end

  def dislike
    if @product.likes.where(user: current_user).destroy_all
      redirect_to :back, notice: "DisLiked!!"
    else
      redirect_to :back, notice: "Error: No Disliked!"
    end
  end

  private
    def set_product
      @product = Product.published.find(params[:id])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= simple_form_for [:admin, @product], :html => { :class => 'form-vertical' } do |f| %>
  <%= f.association :category, prompt: 'Selecione a categoria' %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :price_promo %>
  <%= f.input :status %>


  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_products_path, :class => 'btn btn-default' %>
<% end %>

app/views/admin/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <%= link_to t('.new', :default => t("helpers.links.new")), new_admin_product_path, :class => 'btn btn-primary pull-right' if permitted_to? :create, :admin_products %>
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:category_id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:price_promo) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <% if permitted_to? :manage, :admin_products %>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end -%>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.id, admin_product_path(product) %></td>
        <td><%= product.category_id %></td>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= number_to_currency product.price %></td>
        <td><%= number_to_currency product.price_promo %></td>
        <td nowrap="nowrap"><%=show_status product.status %></td>
        <td nowrap="nowrap"><%=l product.created_at %></td>
        <% if permitted_to? :manage, :admin_products %>
        <td nowrap="nowrap">
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_product_path(product), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
        <% end -%>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:category_id) %>:</strong></dt>
  <dd><%= @product.category_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @product.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @product.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @product.status %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              admin_products_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_product_path(@product), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>