config/routes.rb
Rails.application.routes.draw do

  get '/contatos' => 'contatos#index', as: :contatos

  resources :products, only: [:index, :show] do

    member do 
      get :like  
      get :dislike
    end

  end

  namespace :admin do
  	root 'products#index'
    
    resources :categories do
      member do
        patch :ativar   
        patch :desativar
        patch :change_status 
      end

      collection do

      end
    end

    resources :posts
    resources :products
    resources :users
  end

  devise_for :users, controllers: {:registrations => "users/registrations"}

  root 'products#index'
end

app/models/category.rb
class Category < ActiveRecord::Base

	## RELATIONSHIPS
	has_many :products


	## VALIDATIONS
	validates :name, presence: true
	validates :name, length: { minimum: 5, maximum: 25 }
end

app/controllers/admin/categories_controller.rb
class  Admin::CategoriesController < AdminController
	before_action :set_category, only: [:show, :edit, :update, :destroy, :ativar, :desativar, :change_status]

	def index
		@categories = Category.all
	end

	def show
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		
		if @category.save
			redirect_to admin_categories_path, notice: 'A categoria foi cadastrada com sucesso!'
		else
			render :new
		end

	end

	def edit
		
	end

	def update
		if @category.update(category_params)
			redirect_to admin_categories_path, notice: 'A categoria foi atualizada com sucesso!'
		else
			render :edit
		end
	end

	def destroy
		@category.destroy
		redirect_to admin_categories_path, notice: 'A categoria foi excluída com sucesso!'

	end

	def ativar
		@category.update(status: true)
		redirect_to admin_categories_path, notice: 'A categoria foi ativada com sucesso!'
	end

	def desativar
		@category.update(status: false)
		redirect_to admin_categories_path, notice: 'A categoria foi desativada com sucesso!'
	end

	def change_status
		if @category.status == true
			@category.update(status: false)
			redirect_to admin_categories_path, notice: 'A categoria foi desativada com sucesso!'
		else
			@category.update(status: true)
			redirect_to admin_categories_path, notice: 'A categoria foi ativada com sucesso!'			
		end
	end

	private

		def set_category
			@category = Category.find(params[:id])
		end

		def category_params
			params.require(:category).permit(:name, :status)
		end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_action :set_category, only: [:show, :edit, :update, :destroy]


	def index
		@categories = Category.all
	end

	def show
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		
		if @category.save
			redirect_to categories_path, notice: 'A categoria foi cadastrada com sucesso!'
		else
			render :new
		end

	end

	def edit
		
	end

	def update
		if @category.update(category_params)
			redirect_to categories_path, notice: 'A categoria foi atualizada com sucesso!'
		else
			render :edit
		end
	end

	def destroy
		@category.destroy
		redirect_to categories_path, notice: 'A categoria foi excluída com sucesso!'

	end

	private

		def set_category
			@category = Category.find(params[:id])
		end

		def category_params
			params.require(:category).permit(:name, :status)
		end

end

app/views/categories/edit.html.erb
<h1>Editar Categoria</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<div class="page-header">
	<%= link_to "Cadastrar", new_category_path, class: 'btn btn-primary pull-right' %>
	<h1>Categorias</h1>
</div>


<table class="table">
	<thead>
		<tr>
			<th width="20">id</th>
			<th>name</th>
			<th width="200">created_at</th>
			<th width="200">updated_at</th>
			<th width="200">options</th>
		</tr>	
	</thead>
	
	<tbody>
		<% @categories.each do |category| %>
		<tr>
			<td><%= category.id %></td>
			<td><%= category.name %></td>
			<td><%= category.created_at %></td>
			<td><%= category.updated_at %></td>
			<td nowrap="nowrap">
				<%= link_to 'Show', category_path(category.id), class: 'btn btn-info' %>
				<%= link_to 'Edit', edit_category_path(category.id), class: 'btn btn-primary' %>
				<%= link_to 'Delete', category_path(category.id), method: :delete, data: {confirm: 'Confirma exclusão do registro?'}, class: 'btn btn-danger' %>
				
			</td>
		</tr>
		<% end %>
	</tbody>

</table>

app/views/categories/new.html.erb
<h1>Cadastrar Categoria</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1>Exibindo detalhes da Categoria</h1>

<p>Nome: <%= @category.name %></p>
<p>Status: <%= show_status(@category.status) %></p>
<p>Created_at: <%= @category.created_at %></p>
<p>Updated_at: <%= @category.updated_at %></p>