config/routes.rb
Rails.application.routes.draw do

  get '/contatos' => 'contatos#index', as: :contatos

  resources :products, only: [:index, :show] do

    member do 
      get :like  
      get :dislike
    end

  end

  namespace :admin do
  	root 'products#index'
    
    resources :categories do
      member do
        patch :ativar   
        patch :desativar
        patch :change_status 
      end

      collection do

      end
    end

    resources :posts
    resources :products
    resources :users
  end

  devise_for :users, controllers: {:registrations => "users/registrations"}

  root 'products#index'
end

app/models/category.rb
class Category < ActiveRecord::Base

	## RELATIONSHIPS
	has_many :products


	## VALIDATIONS
	validates :name, presence: true
	validates :name, length: { minimum: 5, maximum: 25 }
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state
  has_many :profiles
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
end

app/models/permission.rb
class Permission < ActiveRecord::Base
	## RELATIONSHIPS
	belongs_to :role
	belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base

	## RELATIONSHIPS
	belongs_to :category
	has_many :likes

	## VALIDATIONS
	validates :category_id, presence: true

	## SCOPE
	scope :published, -> { where(status: true) }
	scope :unpublished, -> { where(status: false) }

	## PRICE_VIEW

	def price_view
		if price_promo.present?
			price_promo
		else
			price
		end
	end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :city
  belongs_to :user

  validates :fullname, presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
	# RELATIONSHIPS
	has_many :permissions
	has_many :users, :through => :permissions

	# VALIDATIONS
	validates :name, uniqueness: true
end

app/models/state.rb
class State < ActiveRecord::Base
	has_many :cities
end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable

	# RELATIONSHIPS
	has_many :permissions
	has_many :roles, :through => :permissions
	has_one  :profile, :dependent => :destroy, :inverse_of => :user
	accepts_nested_attributes_for :profile, :allow_destroy => true
	has_many :likes


	# Inicialização Relacionamento
	after_initialize do
		self.profile ||= self.build_profile()
	end


  	# DECLARATIVE AUTHORIZATION
	def role_symbols
		(roles || []).map{|r| r.name.underscore.to_sym}
	end	

	# CALLBACKS
	before_create :set_client_role_as_default_permission

	# ACIDIONANDO A PERMISSÃO DE CLIENTE COMO PADRÃO
	def set_client_role_as_default_permission
		self.roles << Role.find(3)
	end	
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	# Barreira do Devise
	before_action :authenticate_user!

	# Barreira do Declarative Authorization para todas as actions deste controller
	filter_access_to :all

	# Filtro do declarative authorization para todos os controllers da parte ADMIN
	before_filter { |c| Authorization.current_user = c.current_user }

	#mensagem em caso de usuário não autorizado
	protected
		def permission_denied
			flash[:error] = t("declarative_authorization.permission_denied")
			redirect_to request.referer.present? ? :back : root_url
		end	
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_action :set_category, only: [:show, :edit, :update, :destroy]


	def index
		@categories = Category.all
	end

	def show
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		
		if @category.save
			redirect_to categories_path, notice: 'A categoria foi cadastrada com sucesso!'
		else
			render :new
		end

	end

	def edit
		
	end

	def update
		if @category.update(category_params)
			redirect_to categories_path, notice: 'A categoria foi atualizada com sucesso!'
		else
			render :edit
		end
	end

	def destroy
		@category.destroy
		redirect_to categories_path, notice: 'A categoria foi excluída com sucesso!'

	end

	private

		def set_category
			@category = Category.find(params[:id])
		end

		def category_params
			params.require(:category).permit(:name, :status)
		end

end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
	def index
		
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :status)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:like, :dislike]
  before_action :set_product, only: [:show, :like, :dislike]

  def index
    @products = Product.published
  end

  def show
  end

  def like
    if @product.likes.create!(user: current_user)
      redirect_to :back, notice: "Liked!!"
    else
      redirect_to :back, notice: "Error: No Liked!"
    end
  end

  def dislike
    if @product.likes.where(user: current_user).destroy_all
      redirect_to :back, notice: "DisLiked!!"
    else
      redirect_to :back, notice: "Error: No Disliked!"
    end
  end

  private
    def set_product
      @product = Product.published.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def show_status(valor)
        if valor == true
          '<span style="color:green">Publicado</span>'.html_safe
        elsif valor == false
          '<span style="color:red">Não Publicado</span>'.html_safe
        else
          'Indefinido'	
        end
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_admin_navbar.html.erb
<%= nav_bar fixed: :top, brand: "Ruby Store", responsive: true do %>
  <%= menu_group do %>
      <%= menu_item "Site", root_path, target: '_blank' %>      

      <%= menu_item "Categorias", admin_categories_path  if permitted_to? :manage, :admin_categories %>
      <%= menu_item "Posts", admin_posts_path  if permitted_to? :manage, :admin_posts %>
      <%= menu_item "Produtos", admin_products_path  if permitted_to? :manage, :admin_products %>
      <%= menu_item "Usuários", admin_users_path  if permitted_to? :manage, :admin_users %>

  <% end -%>

  <%= menu_group :pull => :right do %>

    <%= drop_down 'Minha Conta' do %>
      <%= menu_item 'Editar Perfil', edit_user_registration_path %>
    <% end %>        
    <%= menu_item "<i class=\"fa fa-power-off\"></i> Sair".html_safe, destroy_user_session_path, :method => Devise.sign_out_via %>
  <% end -%>
  
<% end -%>

app/views/layouts/_navbar.html.erb
<%= nav_bar fixed: :top, brand: "Ruby Store", responsive: true do %>
  <%= menu_group do %>
      <%= menu_item "Home", root_path %>
      
      <%= menu_item "Produtos", products_path %>
      <%= menu_item "Contatos", contatos_path %>
  <% end -%>

  <%= menu_group :pull => :right do %>
      <% if user_signed_in? %>
        <%= drop_down 'Minha Conta' do %>
          <%= menu_item 'Editar Perfil', edit_user_registration_path %>
        <% end %>        
          <%= menu_item "<i class=\"fa fa-power-off\"></i> Sair".html_safe, destroy_user_session_path, :method => Devise.sign_out_via %>
      <% else %>
          <%= menu_item "<i class=\"fa fa-power-off\"></i> Entrar".html_safe, new_user_session_path %>
      <% end %>
  <% end -%>
  
<% end -%>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RubyStore / Admin" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "admin", :media => "all" %>

    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>


    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

  <%= render 'layouts/admin_navbar' -%>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RubyStore" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

	<%= render 'layouts/navbar' -%>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/application_exemplo.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Ruby Store</title>
	<%= stylesheet_link_tag 'application' %>
	<%= csrf_meta_tags %>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->	
</head>
<body>

	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#">Ruby Store</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Categorias", categories_path %></li>
			<li><%= link_to "Posts", posts_path %></li>
			<li><%= link_to "Contatos", contatos_path %></li>
	      </ul>



	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>




	<div class="container">
		<%= notice %>
		
		<%= yield %>
	</div>

	<%= debug params %>

	<%= javascript_include_tag "application" %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Seja bem-vindo ao projeto RubyStore</h1>